"""Minify ``siteprobe_js.SITE_PROBE_SOURCE`` into ``SITE_PROBE_JS`` (dev-time only).

Run after editing the probe source::

    python scripts/build_probe.py [path/to/esbuild]

It pipes the readable source through ``esbuild --minify`` and rewrites the generated tail of
``siteprobe_js.py`` (the minified script + the SHA-256 of the source it came from). The test suite
fails when the recorded hash doesn't match the source, so a forgotten rebuild can't ship.
esbuild is a dev tool here, never a runtime dependency: the plugin ships the minified string.
"""

from __future__ import annotations

import hashlib
import importlib.util
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "siteprobe_js.py"
MARKER = "# ── generated by scripts/build_probe.py"


_REGEX_AFTER = set("(,=:[!&|?{};+-*%<>~^")


def single_quote(js: str) -> str:
    """Rewrite double-quoted string literals as single-quoted ones where that needs no escaping.

    On Windows every ``"`` in an argv element costs a backslash; esbuild prefers double quotes.
    A small tokenizer over esbuild's output: strings, template literals and regex literals are
    skipped intact; a ``"…"`` literal containing no ``'`` and no escaped ``\"`` becomes ``'…'``.
    """
    out, i, n = [], 0, len(js)
    prev = ""  # last significant non-space char outside literals
    while i < n:
        c = js[i]
        if c in "\"'`":
            j = i + 1
            while j < n and js[j] != c:
                j += 2 if js[j] == "\\" else 1
            lit = js[i:j + 1]
            if c == '"' and "'" not in lit and '\\"' not in lit:
                lit = "'" + lit[1:-1] + "'"
            out.append(lit)
            i = j + 1
            prev = c
            continue
        if c == "/" and (prev in _REGEX_AFTER or prev == "" or re.search(r"(return|typeof|case|in|of)\s*$", "".join(out[-3:]))):
            j, cls = i + 1, False
            while j < n:
                ch = js[j]
                if ch == "\\":
                    j += 2
                    continue
                if ch == "[":
                    cls = True
                elif ch == "]":
                    cls = False
                elif ch == "/" and not cls:
                    break
                j += 1
            j += 1
            while j < n and js[j].isalpha():
                j += 1
            out.append(js[i:j])
            i = j
            prev = "/"
            continue
        out.append(c)
        if not c.isspace():
            prev = c
        i += 1
    return "".join(out)


def main() -> int:
    spec = importlib.util.spec_from_file_location("siteprobe_js_build", TARGET)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    src = mod.SITE_PROBE_SOURCE
    esbuild = (sys.argv[1] if len(sys.argv) > 1 else None) or os.environ.get("ESBUILD") or shutil.which("esbuild")
    if not esbuild:
        print("esbuild not found — pass its path (e.g. ~/dev/protoAgent/node_modules/.bin/esbuild)", file=sys.stderr)
        return 2
    res = subprocess.run([esbuild, "--minify", "--loader=js", "--target=es2022", "--charset=utf8"], input=src, capture_output=True, text=True, check=False)
    if res.returncode:
        print(res.stderr, file=sys.stderr)
        return res.returncode
    js = single_quote(res.stdout.strip().rstrip(";"))
    if "__DS_PREFIX__" not in js or "__CAP__" not in js:
        print("placeholders lost in minification", file=sys.stderr)
        return 3
    text = TARGET.read_text(encoding="utf-8")
    head = text[: text.index(MARKER)]
    tail = (
        f"{MARKER} from SITE_PROBE_SOURCE — never edit by hand ──\n"
        "# The minified form is what ships: browser_eval passes the script on the agent-browser command\n"
        "# line, and Windows' CreateProcess caps a whole command line at 32,767 characters.\n"
        f'SOURCE_SHA256 = "{hashlib.sha256(src.encode()).hexdigest()}"\n'
        f"SITE_PROBE_JS = {js!r}\n"
    )
    TARGET.write_text(head + tail, encoding="utf-8")
    print(f"source {len(src)} chars → minified {len(js)} chars")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
